name: Mirror to Second GitHub

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to second GitHub
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/dilshan-piyathilke/JobSphere.git

          git push --force mirror HEAD:main