name: Mirror to Second GitHub

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/dilshan-piyathilke/JobSphere.git

          git push mirror main --force